/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class AdminDetailEmpInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDetailEmpInfo.class.getName());

    /**
     * Creates new form AdminDetailEmpInfo
     */
    public AdminDetailEmpInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_p = new javax.swing.JPanel();
        searchField_l = new javax.swing.JLabel();
        searchField_cb = new javax.swing.JComboBox<>();
        value_l = new javax.swing.JLabel();
        value_tf = new javax.swing.JTextField();
        empty_p2 = new javax.swing.JPanel();
        bt_search = new javax.swing.JButton();
        empty_p = new javax.swing.JPanel();
        jsp_empTable = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("상세 조회");

        search_p.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        search_p.setLayout(new java.awt.GridLayout(3, 2, 0, 5));

        searchField_l.setText("검색 필드 :");
        search_p.add(searchField_l);

        searchField_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "사번", "이름", "직급", "부서", "연락처", "이메일", "입사일" }));
        search_p.add(searchField_cb);

        value_l.setText("값 입력 :");
        search_p.add(value_l);
        search_p.add(value_tf);

        empty_p2.setPreferredSize(new java.awt.Dimension(393, 20));

        javax.swing.GroupLayout empty_p2Layout = new javax.swing.GroupLayout(empty_p2);
        empty_p2.setLayout(empty_p2Layout);
        empty_p2Layout.setHorizontalGroup(
            empty_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        empty_p2Layout.setVerticalGroup(
            empty_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        search_p.add(empty_p2);

        bt_search.setText("검색");
        search_p.add(bt_search);

        getContentPane().add(search_p, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout empty_pLayout = new javax.swing.GroupLayout(empty_p);
        empty_p.setLayout(empty_pLayout);
        empty_pLayout.setHorizontalGroup(
            empty_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        empty_pLayout.setVerticalGroup(
            empty_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(empty_p, java.awt.BorderLayout.PAGE_END);

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "사번", "이름", "직급", "부서", "연락처", "이메일", "입사일"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp_empTable.setViewportView(empTable);

        getContentPane().add(jsp_empTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDetailEmpInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_search;
    private javax.swing.JTable empTable;
    private javax.swing.JPanel empty_p;
    private javax.swing.JPanel empty_p2;
    private javax.swing.JScrollPane jsp_empTable;
    private javax.swing.JComboBox<String> searchField_cb;
    private javax.swing.JLabel searchField_l;
    private javax.swing.JPanel search_p;
    private javax.swing.JLabel value_l;
    private javax.swing.JTextField value_tf;
    // End of variables declaration//GEN-END:variables
}
