/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class VacAdd extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VacAdd.class.getName());

    /**
     * Creates new form VacAdd
     */
    public VacAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empno_p = new javax.swing.JPanel();
        empno_l = new javax.swing.JLabel();
        empno_tf = new javax.swing.JTextField();
        vacKind_p = new javax.swing.JPanel();
        vacKind_l = new javax.swing.JLabel();
        vacKind_cb = new javax.swing.JComboBox<>();
        startDate_P = new javax.swing.JPanel();
        startDate_l = new javax.swing.JLabel();
        year_cb = new javax.swing.JComboBox<>();
        year_l = new javax.swing.JLabel();
        month_cb = new javax.swing.JComboBox<>();
        month_l = new javax.swing.JLabel();
        day_cb = new javax.swing.JComboBox<>();
        day_l = new javax.swing.JLabel();
        remainVac_p = new javax.swing.JPanel();
        remainVac_l = new javax.swing.JLabel();
        remainVac_l2 = new javax.swing.JLabel();
        vacLong_p = new javax.swing.JPanel();
        vacLong_l = new javax.swing.JLabel();
        vacLong_cb = new javax.swing.JComboBox<>();
        south_p = new javax.swing.JPanel();
        bt_add = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("휴가 신청");
        setPreferredSize(new java.awt.Dimension(510, 364));
        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        empno_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        empno_l.setText("사원 번호 :");
        empno_p.add(empno_l);
        empno_p.add(empno_tf);

        getContentPane().add(empno_p);

        vacKind_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        vacKind_l.setText("휴가 종류 :");
        vacKind_p.add(vacKind_l);

        vacKind_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "연차", "반차" }));
        vacKind_p.add(vacKind_cb);

        getContentPane().add(vacKind_p);

        startDate_P.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        startDate_l.setText("휴가 시작일 :");
        startDate_P.add(startDate_l);

        year_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        startDate_P.add(year_cb);

        year_l.setText("년");
        startDate_P.add(year_l);

        month_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        startDate_P.add(month_cb);

        month_l.setText("월");
        startDate_P.add(month_l);

        day_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        startDate_P.add(day_cb);

        day_l.setText("일");
        startDate_P.add(day_l);

        getContentPane().add(startDate_P);

        remainVac_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        remainVac_l.setText("남은 휴가일 :");
        remainVac_p.add(remainVac_l);

        remainVac_l2.setBackground(new java.awt.Color(255, 255, 255));
        remainVac_l2.setText("남은 휴가일");
        remainVac_l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        remainVac_l2.setOpaque(true);
        remainVac_p.add(remainVac_l2);

        getContentPane().add(remainVac_p);

        vacLong_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        vacLong_l.setText("휴가 기간 (일) :");
        vacLong_p.add(vacLong_l);

        vacLong_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        vacLong_p.add(vacLong_cb);

        getContentPane().add(vacLong_p);

        south_p.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        bt_add.setText("신청");
        south_p.add(bt_add);

        bt_cancel.setText("취소");
        south_p.add(bt_cancel);

        getContentPane().add(south_p);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VacAdd().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JComboBox<String> day_cb;
    private javax.swing.JLabel day_l;
    private javax.swing.JLabel empno_l;
    private javax.swing.JPanel empno_p;
    private javax.swing.JTextField empno_tf;
    private javax.swing.JComboBox<String> month_cb;
    private javax.swing.JLabel month_l;
    private javax.swing.JLabel remainVac_l;
    private javax.swing.JLabel remainVac_l2;
    private javax.swing.JPanel remainVac_p;
    private javax.swing.JPanel south_p;
    private javax.swing.JPanel startDate_P;
    private javax.swing.JLabel startDate_l;
    private javax.swing.JComboBox<String> vacKind_cb;
    private javax.swing.JLabel vacKind_l;
    private javax.swing.JPanel vacKind_p;
    private javax.swing.JComboBox<String> vacLong_cb;
    private javax.swing.JLabel vacLong_l;
    private javax.swing.JPanel vacLong_p;
    private javax.swing.JComboBox<String> year_cb;
    private javax.swing.JLabel year_l;
    // End of variables declaration//GEN-END:variables
}
