/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 *
 * @author zhfja
 */
public class WorkLogWrite extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkLogWrite.class.getName());

    /**
     * Creates new form WorkLogWrite
     */
    public WorkLogWrite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp_workLogWrite = new javax.swing.JScrollPane();
        ta_workLogWrite = new javax.swing.JTextArea();
        bar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("업무 일지 작성");

        jsp_workLogWrite.setPreferredSize(new java.awt.Dimension(410, 521));

        ta_workLogWrite.setRows(5);
        jsp_workLogWrite.setViewportView(ta_workLogWrite);

        getContentPane().add(jsp_workLogWrite, java.awt.BorderLayout.CENTER);

        menu.setText("파일");

        menuItem.setText("저장");
        menu.add(menuItem);

        bar.add(menu);

        setJMenuBar(bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WorkLogWrite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bar;
    private javax.swing.JScrollPane jsp_workLogWrite;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuItem;
    private javax.swing.JTextArea ta_workLogWrite;
    // End of variables declaration//GEN-END:variables
}
